openapi: 3.0.0

info:
  version: "2.0.0"
  title: "RNAget Extension for BeaconV2 API"
  contact:
    email: "emilio.righi@crg.eu"

tags:
- name: "matrices"
- name: "features"
- name: "biosamples"

paths:     
  /biosamples:
    get:
      tags:
        - "biosamples"
      summary: "Endpoint to retrieve a paginated list of biosamples"
      parameters:
        - in: 'query'
          name: 'skip'
          schema:
            type: 'number'
            default: 0
        - in: 'query'
          name: 'limit'
          schema:
            type: 'number'
            default: 10
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/BioSample"
                  total:
                    type: "number"

  /biosamples/{id}:
    get:
      tags:
        - "biosamples"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BioSample"
        "404":
          description: "BioSample not found"

  /biosamples/{id}/matrices:
    get:
      tags:
        - "biosamples"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Matrix"
                  total:
                    type: "number"
        "404":
          description: "BioSample not found"
                  
  /features:
    get:
      tags:
        - "features"
      summary: "Endpoint to retrieve a paginated list of features"
      parameters:
        - in: 'query'
          name: 'skip'
          schema:
            type: 'number'
            default: 0
        - in: 'query'
          name: 'limit'
          schema:
            type: 'number'
            default: 20
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Feature"
                  total:
                    type: "number"

  /features/{id}:
    get:
      tags:
        - "features"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: 'string'
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
        "404":
          description: "Feature not found"

  /features/{id}/matrices:
    get:
      tags:
        - "features"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Matrix"
                  total:
                    type: "number"
        "404":
          description: "Feature not found"
  /matrices:
    get:
      tags:
        - "matrices"
      summary: "Endpoint to retrieve a paginated list of matrices"
      parameters:
        - in: 'query'
          name: 'skip'
          schema:
            type: 'number'
            default: 0
        - in: 'query'
          name: 'limit'
          schema:
            type: 'number'
            default: 20
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Matrix"
                  total:
                    type: "number"

  /matrices/{id}:
    get:
      tags:
        - "matrices"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:  
            type: 'string'

      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Matrix"
        "404":
          description: "Matrix not found"

  /matrices/{id}/features:
    get:
      tags:
        - "matrices"
      summary: "Endpoint to retrieve a paginated list of features from a matrix id"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:  
            type: 'string'
        - in: 'query'
          name: 'skip'
          schema:
            type: 'number'
            default: 0
        - in: 'query'
          name: 'limit'
          schema:
            type: 'number'
            default: 20
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Feature"
                  total:
                    type: "number"
        "404":
          description: "Matrix not found"

  /matrices/{id}/biosamples:
    get:
      tags:
        - "matrices"
      summary: "Endpoint to retrieve a paginated list of biosamples from a matrix id"
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:  
            type: 'string'
        - in: 'query'
          name: 'skip'
          schema:
            type: 'number'
            default: 0
        - in: 'query'
          name: 'limit'
          schema:
            type: 'number'
            default: 10
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/BioSample"
                  total:
                    type: "number"
        "404":
          description: "Matrix not found"


components:

  schemas:

    BioSample:
      type: "object"
      description: "BioSample properties"
      properties:
        id:
          type: "string"
        matrices:
          type: "array"
          items:
            type: "string"
          description: "list of matrix ids"
  
    Feature:
      type: "object"
      description: "Feature properties"
      properties:
        id:
          type: "string"
        molecularType:
          $ref: "#/components/schemas/OntologyTerm"
          description: "Sequence ontology identifier"
        biologicalFunctions:
          type: "array"
          items:
            $ref: "#/components/schemas/OntologyTerm"
          description: "list of ontologies"
        matrices:
          type: "array"
          items:
            type: "string"
          description: "list of matrix ids"
    
    Matrix:
      type: "object"
      description: "Matrix properties"
      properties:
        id:
          type: "string"
        name: 
          type: "string"
        description: 
          type: "string"
        downloadLink:
          type: "string"
        unit:
          type: "string"
          enum:
            - "TPM"
            - "RPM"
            - "RPKM"
            - "FPKM"
            - "raw"
        taxID:
          type: "number"       
        refereceAnnotation:
          type: "string"
        featuresCount:
          type: "number"
        biosamplesCount:
          type: "number"   
          
    ExpressionValue:
      type: "object"
      properties:
        matrixID:
          type: "string"
        sequenceID:
          type: "string"
        biosampleID:
          type: "string"
        value:
          type: "number"
          
    OntologyTerm:
      type: "object"
      properties:
        id:
          type: "string"
          description: "CURIE identifier"
        label:
          type: "string"